spring:
  profiles:
    active: whois
  application.name: VMPlugger
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: Evilcore9320
    url: jdbc:postgresql://localhost:5432/postgres

server.port: 9000
query.link: 'https://rest.db.ripe.net/search.json?source=ripe&flags=no-referenced&type-filter=inetnum&query-string='
connect.timeout.in.seconds: 5
read.timeout.in.seconds: 60
storage.address: http://localhost:9001
kvm.list.address: http://localhost:9001
registrator.address: http://localhost:9000/domain/register
cron.expression: '0 0 9 * * *'
mail-sender:
  host: ${MAIL_SENDER_HOST}
  port: ${MAIL_SENDER_PORT}
  username: ${MAIL_SENDER_USERNAME}
  password: ${MAIL_SENDER_PASSWORD}
  protocol: ${MAIL_SENDER_PROTOCOL}
  auth: ${MAIL_SENDER_AUTH}
  starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE}
  debug: ${MAIL_SENDER_DEBUG}