spring:
  application.name: VMPlugger
  profiles.active: jpa
  datasource:
    username: SA
    password: ""
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl
server.port: 9000

connect.timeout.in.seconds: 30
read.timeout.in.seconds: 60
storage.address: http://localhost:9001
kvm.list.address: http://localhost:9001
