spring:
  application.name: VMPlugger
  profiles.active: mq
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
  datasource:
    username: SA
    password: ""
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
server.port: 9000

connect.timeout.in.seconds: 30
read.timeout.in.seconds: 60
storage.address: http://localhost:9001
kvm.list.address: http://localhost:9001
cron.expression: '0 * * * * *'
registrator.address: http://localhost:9000/domain/register
